### ISSUE TITLE
Tech_input_spilt Error from more than 1 technology with 2 or more input commodities

### ISSUE THREAD

**Issue by hwacc-y** [arfc/pygenesys#36]
The error came from running genesys --infile cookie_example_unfinished.py. Through running the various versions of the input file, the error was traced to the secondary mixer used in the bakery model. The code for the secondary mixer should be correct as it was a version of the original mixer's code with modified variables. The secondary mixer object does not cause any errors when the input commodities and efficiencies are singular.  Also duplicate sqlite file has been ruled out as the possible cause for the error. The exact error message is as follows:

C:\Users\Nicholas\Documents\GitHub\bakery-model>genesys --infile cookie_example_unfinished.py
Reading input from cookie_example_unfinished.py

Database will be exported to C:\Users\Nicholas\Documents\GitHub\bakery-model/pygen_test/bakery_test_kitchen_01.sqlite

Traceback (most recent call last):
  File "C:\Users\Nicholas\AppData\Local\Programs\Python\Python310\Scripts\genesys-script.py", line 33, in <module>
    sys.exit(load_entry_point('pygenesys', 'console_scripts', 'genesys')())
  File "c:\users\nicholas\documents\github\pygenesys\pygenesys\driver.py", line 219, in main
    model._write_sqlite_database()
  File "c:\users\nicholas\documents\github\pygenesys\pygenesys\model_info.py", line 191, in _write_sqlite_database
    create_efficiency(conn, self.technologies, self.time_horizon)
  File "c:\users\nicholas\documents\github\pygenesys\pygenesys\utils\db_creator.py", line 642, in create_efficiency
    create_tech_input_split(connector,
  File "c:\users\nicholas\documents\github\pygenesys\pygenesys\utils\db_creator.py", line 1803, in create_tech_input_split
    cursor.execute(table_command)
sqlite3.OperationalError: table "TechInputSplit" already exists

**Comment by samgdotson** [comment]
Closed by #38
